### ISSUE TITLE
can't build in my win11

### ISSUE THREAD

**Issue by dyexlzc** [bitsdojo/bitsdojo_window#141] opened 2022-02-19 16:52 UTC
here is error info in my computer. seems like windows.dart has some error

my flutter sdk version:
`PS C:\flutter_acrylic\example> flutter --version
Flutter 2.11.0-0.0.pre.494 • channel master • https://github.com/flutter/flutter.git
Framework • revision 312085a19a (10 days ago) • 2022-02-09 15:15:27 +0100
Engine • revision f3ebba540b
Tools • Dart 2.17.0 (build 2.17.0-87.0.dev) • DevTools 2.10.0`

`PS C:\flutter_acrylic\example> flutter run -d windows
Running "flutter pub get" in example...                             6.4s
Launching lib\main.dart on Windows in debug mode...
/D:/code/flutter/flutter_windows_1.22.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window_windows-0.1.0/lib/src/window.dart(2,1): error GF1577525: 'Size' is imported from both 'dart:ffi' and 'dart:ui'. [C:\flutter_acrylic\example\build\windows\flutter\flutter_assemble.vcxproj]
/D:/code/flutter/flutter_windows_1.22.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window_linux-0.1.1/lib/src/window.dart(2,1): error GF1577525: 'Size' is imported from both 'dart:ffi' and 'dart:ui'. [C:\flutter_acrylic\example\build\windows\flutter\flutter_assemble.vcxproj]
/D:/code/flutter/flutter_windows_1.22.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window-0.1.1+1/lib/src/widgets/mouse_state_builder.dart(60,30): warning GBC99161D: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. [C:\flutter_acrylic\example\build\windows\flutter\flutter_assemble.vcxproj]
/D:/code/flutter/flutter_windows_1.22.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window_windows-0.1.0/lib/src/bitsdojo_window_windows_real.dart(17,20): warning GBC99161D: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. [C:\flutter_acrylic\example\build\windows\flutter\flutter_assemble.vcxproj]
/D:/code/flutter/flutter_windows_1.22.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window_macos-0.1.0/lib/src/bitsdojo_window_macos_real.dart(13,20): warning GBC99161D: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. [C:\flutter_acrylic\example\build\windows\flutter\flutter_assemble.vcxproj]
/D:/code/flutter/flutter_windows_1.22.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window_linux-0.1.1/lib/src/bitsdojo_window_linux_real.dart(14,20): warning GBC99161D: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. [C:\flutter_acrylic\example\build\windows\flutter\flutter_assemble.vcxproj]
/D:/code/flutter/flutter_windows_1.22.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window_windows-0.1.0/lib/src/window.dart(72,36): error GF1577525: 'Size' is imported from both 'dart:ffi' and 'dart:ui'. [C:\flutter_acrylic\example\build\windows\flutter\flutter_assemble.vcxproj]
/D:/code/flutter/flutter_windows_1.22.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window_windows-0.1.0/lib/src/window.dart(84,12): error GF1577525: 'Size' is imported from both 'dart:ffi' and 'dart:ui'. [C:\flutter_acrylic\example\build\windows\flutter\flutter_assemble.vcxproj]
/D:/code/flutter/flutter_windows_1.22.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window_windows-0.1.0/lib/src/window.dart(126,12): error GF1577525: 'Size' is imported from both 'dart:ffi' and 'dart:ui'. [C:\flutter_acrylic\example\build\windows\flutter\flutter_assemble.vcxproj]
/D:/code/flutter/flutter_windows_1.22.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window_windows-0.1.0/lib/src/window.dart(133,12): error GF1577525: 'Size' is imported from both 'dart:ffi' and 'dart:ui'. [C:\flutter_acrylic\example\build\windows\flutter\flutter_assemble.vcxproj]
/D:/code/flutter/flutter_windows_1.22.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window_windows-0.1.0/lib/src/window.dart(140,12): error GF1577525: 'Size' is imported from both 'dart:ffi' and 'dart:ui'. [C:\flutter_acrylic\example\build\windows\flutter\flutter_assemble.vcxproj]
/D:/code/flutter/flutter_windows_1.22.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window_windows-0.1.0/lib/src/window.dart(199,22): error GF1577525: 'Size' is imported from both 'dart:ffi' and 'dart:ui'. [C:\flutter_acrylic\example\build\windows\flutter\flutter_assemble.vcxproj]
/D:/code/flutter/flutter_windows_1.22.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window_linux-0.1.1/lib/src/window.dart(93,52): error GF1577525: 'Size' is imported from both 'dart:ffi' and 'dart:ui'. [C:\flutter_acrylic\example\build\windows\flutter\flutter_assemble.vcxproj]
/D:/code/flutter/flutter_windows_1.22.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window_linux-0.1.1/lib/src/window.dart(102,19): error GF1577525: 'Size' is imported from both 'dart:ffi' and 'dart:ui'. [C:\flutter_acrylic\example\build\windows\flutter\flutter_assemble.vcxproj]
/D:/code/flutter/flutter_windows_1.22.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window_linux-0.1.1/lib/src/window.dart(114,12): error GF1577525: 'Size' is imported from both 'dart:ffi' and 'dart:ui'. [C:\flutter_acrylic\example\build\windows\flutter\flutter_assemble.vcxproj]
/D:/code/flutter/flutter_windows_1.22.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window_linux-0.1.1/lib/src/window.dart(145,19): error GF1577525: 'Size' is imported from both 'dart:ffi' and 'dart:ui'. [C:\flutter_acrylic\example\build\windows\flutter\flutter_assemble.vcxproj]
/D:/code/flutter/flutter_windows_1.22.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window_linux-0.1.1/lib/src/window.dart(153,12): error GF1577525: 'Size' is imported from both 'dart:ffi' and 'dart:ui'. [C:\flutter_acrylic\example\build\windows\flutter\flutter_assemble.vcxproj]
/D:/code/flutter/flutter_windows_1.22.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window_linux-0.1.1/lib/src/window.dart(160,12): error GF1577525: 'Size' is imported from both 'dart:ffi' and 'dart:ui'. [C:\flutter_acrylic\example\build\windows\flutter\flutter_assemble.vcxproj]
/D:/code/flutter/flutter_windows_1.22.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window_linux-0.1.1/lib/src/window.dart(228,22): error GF1577525: 'Size' is imported from both 'dart:ffi' and 'dart:ui'. [C:\flutter_acrylic\example\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: “C:\flutter_acrylic\example\build\windows\CMakeFiles\46476b33d7a7a47ca644bc8ce6196c71\flutter_windows.dll.rule;C:\flutter_acrylic\example\build\windows\CMakeFiles\69ff0da7108909aaca01b504e62a70e3\flutter_assemble.rule”的 自定义生成已退出，代码为 1。 [C:\flutter_acrylic\example\build\windows\flutter\flutter_assemble.vcxproj]
Building Windows application...
Exception: Build process failed.
PS C:\flutter_acrylic\example>`

**Comment by CodeDoctorDE** [comment] 2022-02-19 16:53
Please look for other issue before creating a new one. It's another duplicate of #125

**Comment by dyexlzc** [comment] 2022-02-19 17:16
thank you for your reply to solve：）


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bitsdojo/bitsdojo_window"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月20日(星期天) 凌晨0:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bitsdojo/bitsdojo_window] can't build in my win11 (Issue #141)





 
Please look for other issue before creating a new one. It's another duplicate of #125
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CodeDoctorDE** [comment] 2022-02-19 17:17
Bit will fix this in the next week
> Hi everyone,
>
> I've been offline in the past month and a half due to a medical issue but I will have access to my computer next week and I will take a look over the issues.
>
> Bit

**Comment by bitsdojo** [comment] 2022-05-18 17:15
Fixed in `bitsdojo_window: ^0.1.2` - https://github.com/bitsdojo/bitsdojo_window/commit/f320b623db107b03a5976fd88e52ec4fe81fa0c9

Closing this issue. Please re-open if needed.

**Closed by bitsdojo** 2022-05-18 17:15 UTC
