### ISSUE TITLE
Border radius support

### ISSUE THREAD

**Issue by geocine** [bitsdojo/bitsdojo_window#36] opened 2021-03-07 10:50 UTC
Please support changing border radius. Eg. setting border radius to 0 on Mac, setting border radius to >0 on Windows etc.

**Comment by bitsdojo** [comment] 2021-03-11 22:24
Duplicate of https://github.com/bitsdojo/bitsdojo_window/issues/12

**Closed by bitsdojo** 2021-03-11 22:24 UTC
