### ISSUE TITLE
is it possible to support windows 7 which has no GetSystemMetricsForDpi and GetDpiForWindow API?

### ISSUE THREAD

**Issue by skydig** [bitsdojo/bitsdojo_window#92] opened 2021-07-22 19:45 UTC
thanks for you splendid plugin!

**Comment by Maged12** [comment] 2021-08-08 18:25
i have the same inquire

**Comment by bitsdojo** [comment] 2021-08-17 08:12
This is a duplicate of https://github.com/bitsdojo/bitsdojo_window/issues/53

Will be fixed in the next release. Please follow that issue for updates.

**Closed by bitsdojo** 2021-08-17 08:12 UTC
