### ISSUE TITLE
[Feature] Rounded Corners

### ISSUE THREAD

**Issue by prateekmedia** [bitsdojo/bitsdojo_window#89] opened 2021-07-21 20:03 UTC
If this plugin implements it's own custom header bar and border, So would it be possible for this plugin to make the window with rounded corners as it is being introduced in big sur, win 11, etc.

**Comment by Dreta** [comment] 2021-08-02 08:34
A workaround would be to use ClipRRect on the home widget.

**Comment by bitsdojo** [comment] 2021-08-17 08:30
This is a duplicate of https://github.com/bitsdojo/bitsdojo_window/issues/12

Please follow that one for updates.

**Closed by bitsdojo** 2021-08-17 08:30 UTC
Labels: work in progress
